from __future__ import annotations

from settings.app import APP_SETTINGS, AppSettings, get_app_settings
from settings.database import (
    DATABASE_FILENAME as _DATABASE_FILENAME,
    PROPERTY_COLUMN_DEFINITIONS,
    PROPERTY_UNIQUE_CONSTRAINTS,
)
from settings.http import HTTP_HEADERS
from settings.media_cleanup import (
    PROPERTY_MEDIA_DELETE_SELECTED_PHOTOS,
    PROPERTY_MEDIA_DELETE_TEMPORARY_FILES,
)
from settings.images import (
    DEFAULT_PROPERTY_FOLDERS,
    IMAGE_EXTENSIONS,
    IMAGE_HEADERS,
    PROPERTY_MEDIA_RAW_ROOT_DIRNAME,
    PROPERTY_MEDIA_ROOT_DIRNAME,
    RAW_PHOTOS_DIRNAME,
    SELECTED_PHOTOS_DIRNAME,
)
from settings.posters import (
    POSTER_BACKGROUND_BLUR_POWER,
    POSTER_BACKGROUND_BLUR_RADIUS,
    POSTER_HEIGHT,
    POSTER_PHOTO_PANEL_GAP_MIN_PX,
    POSTER_PHOTO_PANEL_GAP_RATIO,
    POSTER_PHOTO_SIDE_MARGIN_MIN_PX,
    POSTER_PHOTO_SIDE_MARGIN_RATIO,
    POSTER_WIDTH,
)
from settings.photo_selection import (
    DEFAULT_PHOTOS_TO_SELECT,
    GEMINI_API_KEY,
    GEMINI_AREA_LABELS,
    GEMINI_AREA_SET,
    GEMINI_EXTERIOR_AREAS,
    GEMINI_MODEL,
    GEMINI_RETRY_ATTEMPTS,
    GEMINI_SELECTION_AUDIT_FILENAME,
    GEMINI_SERVICE_AREAS,
    GEMINI_TIMEOUT_SECONDS,
    GEMINI_VALID_RESULT_AREAS,
)
from settings.reels import (
    ASSETS_DIRNAME,
    REEL_AUDIO_VOLUME,
    REEL_AGENCY_LOGO_SCALE,
    REEL_BACKGROUND_AUDIO_FILENAME,
    REEL_BER_ICON_SCALE,
    REEL_COVER_LOGO_FILENAME,
    REEL_FFMPEG_ENCODER_THREADS,
    REEL_FFMPEG_FILTER_THREADS,
    REEL_FPS,
    REEL_HEIGHT,
    REEL_INTRO_DURATION_SECONDS,
    REEL_MAX_SLIDE_COUNT,
    REEL_SECONDS_PER_SLIDE,
    REEL_SUBTITLE_FONT_PATH,
    REEL_SUBTITLE_FONT_SIZE,
    REEL_TOTAL_DURATION_SECONDS,
    REEL_WIDTH,
)
from settings.social_publishing import (
    GO_HIGH_LEVEL_API_VERSION,
    GO_HIGH_LEVEL_BASE_URL,
    SOCIAL_PUBLISHING_DEFAULT_PLATFORMS,
    SOCIAL_PUBLISHING_DEFAULT_PLATFORM,
    SOCIAL_PUBLISHING_ENABLED,
    SOCIAL_PUBLISHING_LOCAL_ONLY,
    SOCIAL_PUBLISHING_PROPERTY_URL_TEMPLATE,
    SOCIAL_PUBLISHING_PROPERTY_URL_TRACKING_PARAMS,
    SOCIAL_PUBLISHING_POST_STATUS_POLL_ATTEMPTS,
    SOCIAL_PUBLISHING_POST_STATUS_POLL_INTERVAL_SECONDS,
    SOCIAL_PUBLISHING_RETRY_ATTEMPTS,
    SOCIAL_PUBLISHING_RETRY_BACKOFF_SECONDS,
    SOCIAL_PUBLISHING_YOUTUBE_POST_TYPE,
)
DATABASE_FILENAME = _DATABASE_FILENAME
OUTBOUND_HTTP_TIMEOUT_SECONDS = APP_SETTINGS.outbound_http_timeout_seconds
WEBHOOK_HOST = APP_SETTINGS.webhook_host
WEBHOOK_PORT = APP_SETTINGS.webhook_port
WEBHOOK_PATH = APP_SETTINGS.webhook_path
WEBHOOK_SITE_ID_HEADER = APP_SETTINGS.webhook_site_id_header
WEBHOOK_TIMESTAMP_HEADER = APP_SETTINGS.webhook_timestamp_header
WEBHOOK_SIGNATURE_HEADER = APP_SETTINGS.webhook_signature_header
WEBHOOK_GOHIGHLEVEL_LOCATION_ID_HEADER = APP_SETTINGS.webhook_gohighlevel_location_id_header
WEBHOOK_GOHIGHLEVEL_ACCESS_TOKEN_HEADER = APP_SETTINGS.webhook_gohighlevel_access_token_header
WEBHOOK_DISABLE_SECURITY = APP_SETTINGS.webhook_disable_security
WEBHOOK_WORKER_COUNT = APP_SETTINGS.webhook_worker_count
WEBHOOK_JOB_MAX_ATTEMPTS = APP_SETTINGS.webhook_job_max_attempts
WEBHOOK_JOB_RETRY_BACKOFF_SECONDS = APP_SETTINGS.webhook_job_retry_backoff_seconds
WEBHOOK_QUEUE_POLL_INTERVAL_SECONDS = APP_SETTINGS.webhook_queue_poll_interval_seconds
WEBHOOK_QUEUE_LEASE_SECONDS = APP_SETTINGS.webhook_queue_lease_seconds
WEBHOOK_SHUTDOWN_TIMEOUT_SECONDS = APP_SETTINGS.webhook_shutdown_timeout_seconds
WEBHOOK_TIMESTAMP_TOLERANCE_SECONDS = APP_SETTINGS.webhook_timestamp_tolerance_seconds
WEBHOOK_MAX_PAYLOAD_BYTES = APP_SETTINGS.webhook_max_payload_bytes
WEBHOOK_SITE_SECRETS = dict(APP_SETTINGS.webhook_site_secrets)
WEBHOOK_ALLOWED_HOSTS = APP_SETTINGS.webhook_allowed_hosts
WEBHOOK_TRUST_PROXY_HEADERS = APP_SETTINGS.webhook_trust_proxy_headers
WEBHOOK_FORWARDED_ALLOW_IPS = APP_SETTINGS.webhook_forwarded_allow_ips
WEBHOOK_LIMIT_CONCURRENCY = APP_SETTINGS.webhook_limit_concurrency
SQLITE_BUSY_TIMEOUT_MS = APP_SETTINGS.sqlite_busy_timeout_ms
LOG_LEVEL = APP_SETTINGS.log_level
REVIEW_WORKFLOW_ENABLED = APP_SETTINGS.review_workflow_enabled
NOTIFICATIONS_ENABLED = APP_SETTINGS.notifications_enabled
AI_COPY_ENABLED = APP_SETTINGS.ai_copy_enabled
AI_NARRATION_ENABLED = APP_SETTINGS.ai_narration_enabled

__all__ = [
    "APP_SETTINGS",
    "ASSETS_DIRNAME",
    "AI_COPY_ENABLED",
    "AI_NARRATION_ENABLED",
    "AppSettings",
    "DATABASE_FILENAME",
    "DEFAULT_PHOTOS_TO_SELECT",
    "DEFAULT_PROPERTY_FOLDERS",
    "GO_HIGH_LEVEL_BASE_URL",
    "GO_HIGH_LEVEL_API_VERSION",
    "GEMINI_API_KEY",
    "GEMINI_AREA_LABELS",
    "GEMINI_AREA_SET",
    "GEMINI_EXTERIOR_AREAS",
    "GEMINI_MODEL",
    "GEMINI_RETRY_ATTEMPTS",
    "GEMINI_SELECTION_AUDIT_FILENAME",
    "GEMINI_SERVICE_AREAS",
    "GEMINI_TIMEOUT_SECONDS",
    "GEMINI_VALID_RESULT_AREAS",
    "HTTP_HEADERS",
    "IMAGE_EXTENSIONS",
    "IMAGE_HEADERS",
    "OUTBOUND_HTTP_TIMEOUT_SECONDS",
    "PROPERTY_MEDIA_DELETE_SELECTED_PHOTOS",
    "PROPERTY_MEDIA_DELETE_TEMPORARY_FILES",
    "POSTER_HEIGHT",
    "POSTER_BACKGROUND_BLUR_POWER",
    "POSTER_BACKGROUND_BLUR_RADIUS",
    "POSTER_PHOTO_PANEL_GAP_MIN_PX",
    "POSTER_PHOTO_PANEL_GAP_RATIO",
    "POSTER_PHOTO_SIDE_MARGIN_MIN_PX",
    "POSTER_PHOTO_SIDE_MARGIN_RATIO",
    "POSTER_WIDTH",
    "PROPERTY_MEDIA_RAW_ROOT_DIRNAME",
    "PROPERTY_MEDIA_ROOT_DIRNAME",
    "LOG_LEVEL",
    "PROPERTY_COLUMN_DEFINITIONS",
    "PROPERTY_UNIQUE_CONSTRAINTS",
    "RAW_PHOTOS_DIRNAME",
    "REEL_AUDIO_VOLUME",
    "REEL_AGENCY_LOGO_SCALE",
    "REEL_BACKGROUND_AUDIO_FILENAME",
    "REEL_BER_ICON_SCALE",
    "REEL_COVER_LOGO_FILENAME",
    "REEL_FFMPEG_ENCODER_THREADS",
    "REEL_FFMPEG_FILTER_THREADS",
    "REEL_FPS",
    "REEL_HEIGHT",
    "REEL_INTRO_DURATION_SECONDS",
    "REEL_MAX_SLIDE_COUNT",
    "REEL_SECONDS_PER_SLIDE",
    "REEL_SUBTITLE_FONT_PATH",
    "REEL_SUBTITLE_FONT_SIZE",
    "REEL_TOTAL_DURATION_SECONDS",
    "REEL_WIDTH",
    "REVIEW_WORKFLOW_ENABLED",
    "SELECTED_PHOTOS_DIRNAME",
    "SOCIAL_PUBLISHING_DEFAULT_PLATFORMS",
    "SOCIAL_PUBLISHING_DEFAULT_PLATFORM",
    "SOCIAL_PUBLISHING_ENABLED",
    "SOCIAL_PUBLISHING_LOCAL_ONLY",
    "SOCIAL_PUBLISHING_PROPERTY_URL_TEMPLATE",
    "SOCIAL_PUBLISHING_PROPERTY_URL_TRACKING_PARAMS",
    "SOCIAL_PUBLISHING_POST_STATUS_POLL_ATTEMPTS",
    "SOCIAL_PUBLISHING_POST_STATUS_POLL_INTERVAL_SECONDS",
    "SOCIAL_PUBLISHING_RETRY_ATTEMPTS",
    "SOCIAL_PUBLISHING_RETRY_BACKOFF_SECONDS",
    "SOCIAL_PUBLISHING_YOUTUBE_POST_TYPE",
    "NOTIFICATIONS_ENABLED",
    "SQLITE_BUSY_TIMEOUT_MS",
    "WEBHOOK_HOST",
    "WEBHOOK_DISABLE_SECURITY",
    "WEBHOOK_ALLOWED_HOSTS",
    "WEBHOOK_FORWARDED_ALLOW_IPS",
    "WEBHOOK_GOHIGHLEVEL_ACCESS_TOKEN_HEADER",
    "WEBHOOK_GOHIGHLEVEL_LOCATION_ID_HEADER",
    "WEBHOOK_JOB_MAX_ATTEMPTS",
    "WEBHOOK_JOB_RETRY_BACKOFF_SECONDS",
    "WEBHOOK_LIMIT_CONCURRENCY",
    "WEBHOOK_MAX_PAYLOAD_BYTES",
    "WEBHOOK_PATH",
    "WEBHOOK_PORT",
    "WEBHOOK_QUEUE_LEASE_SECONDS",
    "WEBHOOK_QUEUE_POLL_INTERVAL_SECONDS",
    "WEBHOOK_SHUTDOWN_TIMEOUT_SECONDS",
    "WEBHOOK_SIGNATURE_HEADER",
    "WEBHOOK_SITE_ID_HEADER",
    "WEBHOOK_SITE_SECRETS",
    "WEBHOOK_TIMESTAMP_HEADER",
    "WEBHOOK_TIMESTAMP_TOLERANCE_SECONDS",
    "WEBHOOK_TRUST_PROXY_HEADERS",
    "WEBHOOK_WORKER_COUNT",
    "get_app_settings",
]

