from __future__ import annotations


DEFAULT_DATABASE_URL = "postgresql+psycopg://postgres:1234@127.0.0.1:5432/miapp"
DEFAULT_DATABASE_POOL_SIZE = 5
DEFAULT_DATABASE_MAX_OVERFLOW = 10
DEFAULT_DATABASE_POOL_TIMEOUT_SECONDS = 30
# Legacy workspace locator retained for isolated Postgres schemas in tests.
DATABASE_FILENAME = "db.postgres"
DEFAULT_DATABASE_ENCRYPTION_KEY = "BU3oBe_-NJKkqpct_qYxUMm2QkzIUcTdKZGp1YEahGw="


__all__ = [
    "DATABASE_FILENAME",
    "DEFAULT_DATABASE_ENCRYPTION_KEY",
    "DEFAULT_DATABASE_MAX_OVERFLOW",
    "DEFAULT_DATABASE_POOL_SIZE",
    "DEFAULT_DATABASE_POOL_TIMEOUT_SECONDS",
    "DEFAULT_DATABASE_URL",
]
