from __future__ import annotations

from pathlib import Path

from settings.app import APP_SETTINGS


ASSETS_DIRNAME = "assets"
REEL_BER_ICONS_DIRNAME = "ber-icons"

REEL_COVER_LOGO_FILENAME = "ckp-logo.png"
REEL_BACKGROUND_AUDIO_FILENAME = "music/ncs-music.mp3"
REEL_WIDTH = APP_SETTINGS.reel_width
REEL_HEIGHT = APP_SETTINGS.reel_height
REEL_FPS = APP_SETTINGS.reel_fps
REEL_TOTAL_DURATION_SECONDS = APP_SETTINGS.reel_total_duration_seconds
REEL_SECONDS_PER_SLIDE = APP_SETTINGS.reel_seconds_per_slide
REEL_INTRO_DURATION_SECONDS = APP_SETTINGS.reel_intro_duration_seconds
REEL_SUBTITLE_FONT_PATH = Path(APP_SETTINGS.reel_subtitle_font_path).expanduser()
REEL_SUBTITLE_FONT_SIZE = APP_SETTINGS.reel_subtitle_font_size
REEL_MAX_SLIDE_COUNT = 7
REEL_AUDIO_VOLUME = 0.45
REEL_FFMPEG_FILTER_THREADS = APP_SETTINGS.reel_ffmpeg_filter_threads
REEL_FFMPEG_ENCODER_THREADS = APP_SETTINGS.reel_ffmpeg_encoder_threads
REEL_BER_ICON_SCALE = APP_SETTINGS.reel_ber_icon_scale
REEL_AGENCY_LOGO_SCALE = APP_SETTINGS.reel_agency_logo_scale


__all__ = [
    "ASSETS_DIRNAME",
    "REEL_BER_ICONS_DIRNAME",
    "REEL_AUDIO_VOLUME",
    "REEL_AGENCY_LOGO_SCALE",
    "REEL_BACKGROUND_AUDIO_FILENAME",
    "REEL_BER_ICON_SCALE",
    "REEL_COVER_LOGO_FILENAME",
    "REEL_FFMPEG_ENCODER_THREADS",
    "REEL_FFMPEG_FILTER_THREADS",
    "REEL_FPS",
    "REEL_HEIGHT",
    "REEL_INTRO_DURATION_SECONDS",
    "REEL_MAX_SLIDE_COUNT",
    "REEL_SECONDS_PER_SLIDE",
    "REEL_SUBTITLE_FONT_PATH",
    "REEL_SUBTITLE_FONT_SIZE",
    "REEL_TOTAL_DURATION_SECONDS",
    "REEL_WIDTH",
]
