from __future__ import annotations

from settings.app import APP_SETTINGS

GO_HIGH_LEVEL_BASE_URL = APP_SETTINGS.go_high_level_base_url
GO_HIGH_LEVEL_API_VERSION = APP_SETTINGS.go_high_level_api_version
SOCIAL_PUBLISHING_DEFAULT_PLATFORM = APP_SETTINGS.social_publishing_default_platform
SOCIAL_PUBLISHING_ENABLED = bool(APP_SETTINGS.social_publishing_enabled)
SOCIAL_PUBLISHING_LOCAL_ONLY = bool(APP_SETTINGS.social_publishing_local_only)
SOCIAL_PUBLISHING_PROPERTY_URL_TEMPLATE = APP_SETTINGS.social_publishing_property_url_template
SOCIAL_PUBLISHING_PROPERTY_URL_TRACKING_PARAMS = dict(APP_SETTINGS.social_publishing_property_url_tracking_params)
SOCIAL_PUBLISHING_RETRY_ATTEMPTS = APP_SETTINGS.social_publishing_retry_attempts
SOCIAL_PUBLISHING_RETRY_BACKOFF_SECONDS = APP_SETTINGS.social_publishing_retry_backoff_seconds

__all__ = [
    "GO_HIGH_LEVEL_API_VERSION",
    "GO_HIGH_LEVEL_BASE_URL",
    "SOCIAL_PUBLISHING_DEFAULT_PLATFORM",
    "SOCIAL_PUBLISHING_ENABLED",
    "SOCIAL_PUBLISHING_LOCAL_ONLY",
    "SOCIAL_PUBLISHING_PROPERTY_URL_TEMPLATE",
    "SOCIAL_PUBLISHING_PROPERTY_URL_TRACKING_PARAMS",
    "SOCIAL_PUBLISHING_RETRY_ATTEMPTS",
    "SOCIAL_PUBLISHING_RETRY_BACKOFF_SECONDS",
]
