from __future__ import annotations

from settings.app import APP_SETTINGS

GO_HIGH_LEVEL_BASE_URL = APP_SETTINGS.go_high_level_base_url
GO_HIGH_LEVEL_API_VERSION = APP_SETTINGS.go_high_level_api_version
SOCIAL_PUBLISHING_DEFAULT_PLATFORMS = tuple(APP_SETTINGS.social_publishing_default_platforms)
SOCIAL_PUBLISHING_DEFAULT_PLATFORM = (
    SOCIAL_PUBLISHING_DEFAULT_PLATFORMS[0]
    if SOCIAL_PUBLISHING_DEFAULT_PLATFORMS
    else "tiktok"
)
SOCIAL_PUBLISHING_ENABLED = bool(APP_SETTINGS.social_publishing_enabled)
SOCIAL_PUBLISHING_LOCAL_ONLY = bool(APP_SETTINGS.social_publishing_local_only)
SOCIAL_PUBLISHING_PROPERTY_URL_TEMPLATE = APP_SETTINGS.social_publishing_property_url_template
SOCIAL_PUBLISHING_PROPERTY_URL_TRACKING_PARAMS = dict(APP_SETTINGS.social_publishing_property_url_tracking_params)
SOCIAL_PUBLISHING_RETRY_ATTEMPTS = APP_SETTINGS.social_publishing_retry_attempts
SOCIAL_PUBLISHING_RETRY_BACKOFF_SECONDS = APP_SETTINGS.social_publishing_retry_backoff_seconds
SOCIAL_PUBLISHING_YOUTUBE_POST_TYPE = APP_SETTINGS.social_publishing_youtube_post_type
SOCIAL_PUBLISHING_POST_STATUS_POLL_ATTEMPTS = (
    APP_SETTINGS.social_publishing_post_status_poll_attempts
)
SOCIAL_PUBLISHING_POST_STATUS_POLL_INTERVAL_SECONDS = (
    APP_SETTINGS.social_publishing_post_status_poll_interval_seconds
)

__all__ = [
    "GO_HIGH_LEVEL_API_VERSION",
    "GO_HIGH_LEVEL_BASE_URL",
    "SOCIAL_PUBLISHING_DEFAULT_PLATFORMS",
    "SOCIAL_PUBLISHING_DEFAULT_PLATFORM",
    "SOCIAL_PUBLISHING_ENABLED",
    "SOCIAL_PUBLISHING_LOCAL_ONLY",
    "SOCIAL_PUBLISHING_PROPERTY_URL_TEMPLATE",
    "SOCIAL_PUBLISHING_PROPERTY_URL_TRACKING_PARAMS",
    "SOCIAL_PUBLISHING_RETRY_ATTEMPTS",
    "SOCIAL_PUBLISHING_RETRY_BACKOFF_SECONDS",
    "SOCIAL_PUBLISHING_POST_STATUS_POLL_ATTEMPTS",
    "SOCIAL_PUBLISHING_POST_STATUS_POLL_INTERVAL_SECONDS",
    "SOCIAL_PUBLISHING_YOUTUBE_POST_TYPE",
]
