from __future__ import annotations

from settings.app import APP_SETTINGS

WEBHOOK_HOST = APP_SETTINGS.webhook_host
WEBHOOK_PORT = APP_SETTINGS.webhook_port
WEBHOOK_PATH = APP_SETTINGS.webhook_path
WEBHOOK_SITE_ID_HEADER = APP_SETTINGS.webhook_site_id_header
WEBHOOK_TIMESTAMP_HEADER = APP_SETTINGS.webhook_timestamp_header
WEBHOOK_SIGNATURE_HEADER = APP_SETTINGS.webhook_signature_header
WEBHOOK_GOHIGHLEVEL_LOCATION_ID_HEADER = APP_SETTINGS.webhook_gohighlevel_location_id_header
WEBHOOK_GOHIGHLEVEL_ACCESS_TOKEN_HEADER = APP_SETTINGS.webhook_gohighlevel_access_token_header
WEBHOOK_DISABLE_SECURITY = APP_SETTINGS.webhook_disable_security
WEBHOOK_WORKER_COUNT = APP_SETTINGS.webhook_worker_count
WEBHOOK_JOB_MAX_ATTEMPTS = APP_SETTINGS.webhook_job_max_attempts
WEBHOOK_JOB_RETRY_BACKOFF_SECONDS = APP_SETTINGS.webhook_job_retry_backoff_seconds
WEBHOOK_QUEUE_POLL_INTERVAL_SECONDS = APP_SETTINGS.webhook_queue_poll_interval_seconds
WEBHOOK_QUEUE_LEASE_SECONDS = APP_SETTINGS.webhook_queue_lease_seconds
WEBHOOK_SHUTDOWN_TIMEOUT_SECONDS = APP_SETTINGS.webhook_shutdown_timeout_seconds
WEBHOOK_TIMESTAMP_TOLERANCE_SECONDS = APP_SETTINGS.webhook_timestamp_tolerance_seconds
WEBHOOK_MAX_PAYLOAD_BYTES = APP_SETTINGS.webhook_max_payload_bytes
WEBHOOK_SITE_SECRETS = dict(APP_SETTINGS.webhook_site_secrets)

__all__ = [
    "WEBHOOK_HOST",
    "WEBHOOK_DISABLE_SECURITY",
    "WEBHOOK_GOHIGHLEVEL_ACCESS_TOKEN_HEADER",
    "WEBHOOK_GOHIGHLEVEL_LOCATION_ID_HEADER",
    "WEBHOOK_JOB_MAX_ATTEMPTS",
    "WEBHOOK_JOB_RETRY_BACKOFF_SECONDS",
    "WEBHOOK_MAX_PAYLOAD_BYTES",
    "WEBHOOK_PATH",
    "WEBHOOK_PORT",
    "WEBHOOK_QUEUE_LEASE_SECONDS",
    "WEBHOOK_QUEUE_POLL_INTERVAL_SECONDS",
    "WEBHOOK_SHUTDOWN_TIMEOUT_SECONDS",
    "WEBHOOK_SIGNATURE_HEADER",
    "WEBHOOK_SITE_ID_HEADER",
    "WEBHOOK_SITE_SECRETS",
    "WEBHOOK_TIMESTAMP_HEADER",
    "WEBHOOK_TIMESTAMP_TOLERANCE_SECONDS",
    "WEBHOOK_WORKER_COUNT",
]
