"""Create ``email_notifications`` table (feature 26).

Audit + idempotency for outbound email notifications driven by domain
events (currently only ``review_requested``; future kinds reuse the
same table). One row per (agency, site, property, recipient, event)
tuple, enforced by the UNIQUE constraint so the dispatch use case (in
feature 27) can rely on ``ON CONFLICT`` for idempotent inserts.

``id`` is a ``VARCHAR(36)`` to match the convention of every other
aggregate id in this repo (string-encoded UUIDs generated by the
application layer, not native ``UUID`` columns).
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op


revision = "20260514_0007"
down_revision = "20260514_0006"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "email_notifications",
        sa.Column("id", sa.String(length=36), primary_key=True),
        sa.Column(
            "agency_id",
            sa.String(length=36),
            sa.ForeignKey("agencies.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("event_kind", sa.Text(), nullable=False),
        sa.Column("site_id", sa.Text(), nullable=False),
        sa.Column("source_property_id", sa.Integer(), nullable=False),
        sa.Column("recipient_email", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("provider_message_id", sa.Text(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.UniqueConstraint(
            "agency_id",
            "site_id",
            "source_property_id",
            "recipient_email",
            "event_kind",
            name="uq_email_notifications_dedup",
        ),
    )
    op.create_index(
        "idx_email_notifications_status",
        "email_notifications",
        ["status"],
    )
    op.create_index(
        "idx_email_notifications_agency_created",
        "email_notifications",
        ["agency_id", sa.text("created_at DESC")],
    )


def downgrade() -> None:
    op.drop_index(
        "idx_email_notifications_agency_created",
        table_name="email_notifications",
    )
    op.drop_index(
        "idx_email_notifications_status",
        table_name="email_notifications",
    )
    op.drop_table("email_notifications")
